# Generated by Django 5.0.3 on 2025-12-19 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='upload_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
