# Generated by Django 5.0.3 on 2025-12-22 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_receipt_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='upload_date',
        ),
    ]
